# Uncomment the next line to define a global platform for your project
# platform :ios, '15.0'

target 'SpeqAI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpeqAI

  pod 'SwiftOpus', '~> 0.6'
end

target 'SpeqAITests' do
  inherit! :search_paths
  # Pods for testing
end
